import { useState } from "react"
import { Link, useParams } from "react-router-dom"
import { Card, CardHeader } from "../../components/ui/Card"
import { Async, Button, Field, inputClass, Notice } from "../../components/ui/kit"
import { Badge } from "../../components/ui/StatusBadge"
import { useApi } from "../../hooks/useApi"
import { api, ApiRequestError } from "../../lib/api"
import type { GapDetail } from "../../types"

const FEEDBACK_LABEL = { yes: "Looks right", partly: "Partly right", no: "Not quite yet" } as const

export default function GapPage() {
  const { gapId } = useParams()
  const state = useApi<{ gap: GapDetail }>(`/learning/gaps/${gapId}`)
  const [busy, setBusy] = useState<"lesson" | "exercise" | "answer" | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [answer, setAnswer] = useState("")

  const run = async (what: "lesson" | "exercise" | "answer", fn: () => Promise<unknown>) => {
    setBusy(what)
    setError(null)
    try {
      await fn()
      await state.reload()
    } catch (err) {
      setError(err instanceof ApiRequestError ? err.message : "Something went wrong.")
    } finally {
      setBusy(null)
    }
  }

  return (
    <Async state={state}>
      {({ gap }) => (
        <div className="mx-auto max-w-3xl">
          <Link to="/student/learning" className="text-sm font-medium text-ink-500 hover:text-teal-700">← Improve</Link>
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <Badge tone="teal">{gap.skill}</Badge>
            {gap.resolved ? <Badge tone="green">Worked through</Badge> : <Badge tone={gap.severity === "significant" ? "amber" : "neutral"}>{gap.severity}</Badge>}
          </div>
          <h1 className="mt-2 text-2xl font-bold tracking-tight text-ink-950 sm:text-3xl">{gap.title}</h1>
          <p className="mt-2 leading-relaxed text-ink-700">{gap.detail}</p>
          {gap.evidence?.quote && (
            <p className="mt-3 rounded-xl bg-ink-100 px-4 py-2.5 font-mono text-xs text-ink-700">From your {gap.evidence.source === "answer" ? "interview answer" : "code"}{gap.evidence.path ? ` (${gap.evidence.path}${gap.evidence.line ? `:${gap.evidence.line}` : ""})` : ""}: {gap.evidence.quote}</p>
          )}
          <Link to={`/student/work/${gap.runId}`} className="mt-3 inline-block text-sm font-semibold text-teal-700 hover:underline">Back to the work this came from</Link>

          <Notice tone="info" className="mt-6">{gap.notAnAssessment}</Notice>
          {error && <Notice tone="danger" className="mt-4">{error}</Notice>}

          <Card className="mt-6">
            <CardHeader title="Where to learn this" subtitle="Hand-picked resources. Each link is checked when you open this page." />
            <ul className="divide-y divide-ink-100">
              {gap.recommendations.map((r) => (
                <li key={r.id} className="px-5 py-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <a href={r.url} target="_blank" rel="noopener noreferrer" className="font-semibold text-teal-700 hover:underline">{r.title}<span className="sr-only"> (opens in a new tab)</span></a>
                    {r.kind === "search" ? <Badge tone="neutral">Search, not a course</Badge> : r.verified ? <Badge tone="green">Link checked</Badge> : <Badge tone="amber">Couldn't check the link</Badge>}
                  </div>
                  <div className="text-xs text-ink-500">{r.provider}</div>
                  {r.why && <p className="mt-1 text-sm text-ink-600">{r.why}</p>}
                </li>
              ))}
            </ul>
          </Card>

          <Card className="mt-6">
            <CardHeader title="Mini-lesson" subtitle="Written by AI for this gap. Practice material, not an assessment." />
            <p className={`mx-5 mt-1 rounded-xl px-3 py-2 text-xs ${gap.basis.kind === "general" ? "bg-amber-100/60 text-ink-700" : "bg-ink-100 text-ink-600"}`}>{gap.basis.label}</p>
            {gap.lesson ? (
              <div className="space-y-3 px-5 py-4">
                <h3 className="font-semibold text-ink-900">{gap.lesson.title}</h3>
                <p className="whitespace-pre-wrap text-sm leading-relaxed text-ink-700">{gap.lesson.body}</p>
                <ul className="list-disc space-y-1 pl-5 text-sm text-ink-700">{gap.lesson.keyPoints.map((k) => <li key={k}>{k}</li>)}</ul>
                <p className="text-xs text-ink-500">Generated by {gap.lesson.model}. AI can make mistakes — check anything important against the resources above.</p>
              </div>
            ) : (
              <div className="px-5 py-4">
                <Button onClick={() => void run("lesson", () => api.post(`/learning/gaps/${gap.id}/lesson`))} loading={busy === "lesson"}>Write me a short lesson</Button>
              </div>
            )}
          </Card>

          <Card className="mt-6">
            <CardHeader title="Practice exercise" subtitle="Try it, then get feedback. The feedback is for learning only." />
            {gap.exercise ? (
              <div className="space-y-4 px-5 py-4">
                <p className="whitespace-pre-wrap text-sm leading-relaxed text-ink-800">{gap.exercise.prompt}</p>
                {gap.exercise.hints.length > 0 && (
                  <details className="text-sm">
                    <summary className="cursor-pointer font-semibold text-teal-700">Hints</summary>
                    <ul className="mt-1 list-disc pl-5 text-ink-700">{gap.exercise.hints.map((h) => <li key={h}>{h}</li>)}</ul>
                  </details>
                )}
                <form
                  className="space-y-3"
                  onSubmit={(e) => {
                    e.preventDefault()
                    void run("answer", async () => {
                      await api.post(`/learning/exercises/${gap.exercise!.id}/answers`, { answer })
                      setAnswer("")
                    })
                  }}
                >
                  <Field label="Your answer" htmlFor="exercise-answer">
                    <textarea id="exercise-answer" className={`${inputClass} min-h-32 font-mono text-[13px]`} value={answer} onChange={(e) => setAnswer(e.target.value)} maxLength={4000} />
                  </Field>
                  <Button type="submit" loading={busy === "answer"} disabled={answer.trim().length < 5}>Get feedback</Button>
                </form>
                {gap.exercise.responses.map((r) => (
                  <div key={r.id} className="rounded-xl border border-ink-200 p-4 text-sm">
                    <div className="mb-1 flex items-center gap-2"><Badge tone={r.feedback.looksCorrect === "yes" ? "green" : "amber"}>{FEEDBACK_LABEL[r.feedback.looksCorrect]}</Badge><span className="text-xs text-ink-500">Practice feedback — not an assessment</span></div>
                    <pre className="mb-2 max-h-32 overflow-auto rounded-lg bg-ink-100 p-2 font-mono text-xs whitespace-pre-wrap text-ink-700">{r.answer}</pre>
                    {r.feedback.whatWorked.length > 0 && <><div className="font-semibold text-ink-800">What worked</div><ul className="list-disc pl-5 text-ink-700">{r.feedback.whatWorked.map((w) => <li key={w}>{w}</li>)}</ul></>}
                    {r.feedback.toImprove.length > 0 && <><div className="mt-2 font-semibold text-ink-800">To improve</div><ul className="list-disc pl-5 text-ink-700">{r.feedback.toImprove.map((w) => <li key={w}>{w}</li>)}</ul></>}
                    <p className="mt-2 text-ink-700"><strong>Next step:</strong> {r.feedback.nextStep}</p>
                  </div>
                ))}
              </div>
            ) : (
              <div className="px-5 py-4">
                <Button onClick={() => void run("exercise", () => api.post(`/learning/gaps/${gap.id}/exercise`))} loading={busy === "exercise"}>Give me an exercise</Button>
              </div>
            )}
          </Card>
        </div>
      )}
    </Async>
  )
}
