import type { DatabaseSync } from "node:sqlite"
import type { ChallengeSpec, PhaseSpec } from "../domain/spec.ts"
import type { Difficulty } from "../domain/spec.ts"
import { MOCK_PROVIDER } from "../ai/provider.ts"
import { all, exec, newId, nowIso, one, parseList } from "../sql.ts"

export type VersionOrigin = "ai" | "offline_template" | "company_edit" | "demo_fixture"

export interface VersionMeta {
  id: string
  kind: "company" | "practice"
  version: number
  origin: VersionOrigin
  provider: string
  model: string
  promptVersion: string
  parentVersionId: string | null
  createdAt: string
}

export interface StoredVersion extends VersionMeta {
  spec: ChallengeSpec
  /** phase key → phase row id */
  phaseIds: Record<string, string>
}

export interface NewVersion {
  kind: "company" | "practice"
  challengeId?: string
  practiceId?: string
  spec: ChallengeSpec
  origin: VersionOrigin
  provider?: string
  model?: string
  promptVersion?: string
  parentVersionId?: string | null
}

/** Stores a spec as the next version of its challenge/practice. A version is never edited afterwards. */
export function insertVersion(db: DatabaseSync, v: NewVersion): string {
  const owner = v.kind === "company" ? { col: "challenge_id", id: v.challengeId } : { col: "practice_id", id: v.practiceId }
  const next = (one(db, `SELECT COALESCE(MAX(version), 0) + 1 AS n FROM challenge_versions WHERE ${owner.col} = ?`, owner.id ?? "")!.n as number) ?? 1
  const id = newId("ver")
  exec(
    db,
    `INSERT INTO challenge_versions (id, kind, challenge_id, practice_id, version, title, summary, scenario, learning_goals, skills, difficulty, estimated_hours,
       origin, provider, model, prompt_version, parent_version_id, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    id, v.kind, v.challengeId ?? null, v.practiceId ?? null, next, v.spec.title, v.spec.summary, v.spec.scenario,
    JSON.stringify(v.spec.learningGoals), JSON.stringify(v.spec.skills), v.spec.difficulty, v.spec.estimatedHours,
    v.origin, v.provider ?? "", v.model ?? "", v.promptVersion ?? "", v.parentVersionId ?? null, nowIso(),
  )
  v.spec.phases.forEach((p, i) => {
    exec(
      db,
      `INSERT INTO phases (id, version_id, position, key, title, objective, instructions, skills, acceptance_criteria, rubric, deliverables, depends_on, estimated_hours)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      newId("phs"), id, i + 1, p.key, p.title, p.objective, p.instructions, JSON.stringify(p.skills), JSON.stringify(p.acceptanceCriteria),
      JSON.stringify(p.rubric), JSON.stringify(p.deliverables), JSON.stringify(p.dependsOn), p.estimatedHours,
    )
  })
  return id
}

const jsonList = <T>(v: unknown): T[] => {
  try {
    const parsed = JSON.parse(String(v ?? "[]"))
    return Array.isArray(parsed) ? (parsed as T[]) : []
  } catch {
    return []
  }
}

export function loadVersion(db: DatabaseSync, versionId: string): StoredVersion | null {
  const v = one(db, "SELECT * FROM challenge_versions WHERE id = ?", versionId)
  if (!v) return null
  const phaseRows = all(db, "SELECT * FROM phases WHERE version_id = ? ORDER BY position", versionId)
  const phaseIds: Record<string, string> = {}
  const phases: PhaseSpec[] = phaseRows.map((p) => {
    phaseIds[String(p.key)] = String(p.id)
    return {
      key: String(p.key),
      title: String(p.title),
      objective: String(p.objective),
      instructions: String(p.instructions),
      skills: parseList(p.skills),
      acceptanceCriteria: jsonList(p.acceptance_criteria),
      rubric: jsonList(p.rubric),
      deliverables: parseList(p.deliverables),
      dependsOn: parseList(p.depends_on),
      estimatedHours: Number(p.estimated_hours),
    }
  })
  return {
    id: String(v.id),
    kind: v.kind as "company" | "practice",
    version: Number(v.version),
    origin: v.origin as VersionOrigin,
    provider: String(v.provider),
    model: String(v.model),
    promptVersion: String(v.prompt_version),
    parentVersionId: (v.parent_version_id as string | null) ?? null,
    createdAt: String(v.created_at),
    phaseIds,
    spec: {
      title: String(v.title),
      summary: String(v.summary),
      scenario: String(v.scenario),
      learningGoals: parseList(v.learning_goals),
      skills: parseList(v.skills),
      difficulty: v.difficulty as Difficulty,
      estimatedHours: Number(v.estimated_hours),
      phases,
    },
  }
}

export function versionMeta(v: StoredVersion) {
  return {
    id: v.id,
    version: v.version,
    origin: v.origin,
    provider: v.provider,
    model: v.model,
    promptVersion: v.promptVersion,
    createdAt: v.createdAt,
    /** Plain-language label the UI shows next to the content. */
    originLabel:
      v.origin === "ai" && v.provider === MOCK_PROVIDER ? "Demo mock — scripted, not AI-generated" : v.origin === "ai" ? `Generated by AI (${v.model})` : v.origin === "offline_template" ? "Offline template — not AI-generated" : v.origin === "company_edit" ? "Edited by your team" : "Demonstration content",
  }
}
